### ISSUE TITLE
Left speaker plays sound for both speakers

### ISSUE THREAD

**Issue by blueskull** [darinpp/yoga-slim-7#1] opened 2023-11-13 04:00 UTC
Hi Darin, 

Been following your discussion with Shenghao for a while on TI E2E. Sorry I couldn't join the discussion on E2E as I don't have an corporate email address.

Been using the RCA4.bin from both your repo and the two version from E2E page, here's something I've observed that is weird: the left speaker plays sound for both left and right speakers, while the right speaker only plays its own channel. Is there anyway I can fix this?

The kernel I use is 6.6.1, patched with Shenghao's latest ftc.7z.

Computer: Yoga Air 14s (Chinese mainland version of Yoga Slim 7 Gen 8)
OS: Ubuntu 22.04 LTS, Kernel 6.6.1, Gnome Desktop
Audio: PipeWire+WirePlumber, configured with software mixer volume control

Regards, 

Bo Gao

**Comment by darinpp** [comment] 2023-11-16 16:51
Hi Bo,
You are right. I just tested with this file https://www.kozco.com/tech/LRMonoPhase4.wav
and it seems the L/R are actually messed up.

I doubt that these RCA files are actually tested and made with specific Lenovo laptops in mind. The hardware resets that were coded were easy to fix and I just updated the bin file manually.
I see that someone commented on reddit that this may be controlled with 0x0a register. It seems very likely that this is the case and makes sense to test. The RCA4 file is pretty simple and easy to reverse engineer. It is just few lists of writes to registers arranged as power up/down sequence and grouped into programs. For that file that I posted here there are three programs. You can test by using `amixer cset numid=1 <1..3>` to switch the program.

I'm also quite close to have a small tool to make it easy to dump and change the RCA4.bin file. I'll try to add a link to it in the next day or two after it is done. 
The 2781 datasheet is available and it may not be that hard to put a set of register writes that make sense and make the whole thing works as it should.

**Comment by mark-herbert42** [comment] 2023-11-16 21:26
[TIAS2781RCA4-7.json](https://github.com/darinpp/yoga-slim-7/files/13383853/TIAS2781RCA4-7.json)

[TIAS2781RCA4.bin.gz](https://github.com/darinpp/yoga-slim-7/files/13384285/TIAS2781RCA4.bin.gz)


I've tried testing the firmware - the 0a register is taking 1a, 2a, 3a values according to spec for left, right and  mixed. And register 02 allows to switch amp off. So I was switching off all amps keeping just one  running.   And from what I found at least for my Yoga - that channels are wired between left and right not using odd/even numbers , but in order - 1,2 - one side, 3,4 - other side. So I've changed the 0a registers from wiring 1,3/2,4 to wiring 1,2/3,4.
 
The resulting json  and bin is attached - and it seems to work for me.

**Comment by blueskull** [comment] 2023-11-17 03:21
I wrote that Reddit post, but I didn't find time to mess with Shenghao's provided tool. I'm glad to hear that by reassigning channel ID, the new bin file works like a charm. I don't have my Yoga on hand, but I'll test your bin file when I get home.

Cheers

**Comment by darinpp** [comment] 2023-11-17 17:16
@mark-herbert42 The file didn't work for me at a first try. I'll try to debug it over the weekend. Will figure it out. Thanks for fixing it.

**Comment by mark-herbert42** [comment] 2023-11-17 18:17
Strange - but the way it works is not stable. I have all the dirvers built as modules - and in case of issue do unload and load back.  When something goes wrong at initial load or resume from hibernate ( this laptop dopes not suspend to RAM at all) - I run this script. 

runuser -u $PIPEUSER -- pactl set-sink-mute alsa_output.pci-0000_c3_00.6.HiFi__hw_Generic_1__sink 1
rmmod snd_hda_intel
rmmod snd_hda_scodec_tas2781_i2c
rmmod snd_hda_codec_realtek

modprobe snd_hda_codec_realtek
modprobe snd_hda_intel
modprobe  snd_hda_scodec_tas2781_i2c

echo '1' > '/sys/module/snd_hda_intel/parameters/power_save'
runuser -u $PIPEUSER -- pactl set-sink-mute alsa_output.pci-0000_c3_00.6.HiFi__hw_Generic_1__sink 1
killall alsa-controller
sleep 3
/usr/local/bin/alsa-controller > /dev/null 2>&1 &

**Comment by darinpp** [comment] 2023-11-17 19:30
I patched the file that I had checked in from ti.com.
Replaced the writes to 0a to be 1,1,2,2 instead of 1,2,1,2 as they were before. Now everything works and playing the test file routes the L/R to the correct speakers. Thanks. I also kept the fix to 5c to not use hardware shutdowns which makes it less jerky when starting a playback.
Thanks @mark-herbert42

**Comment by blueskull** [comment] 2023-11-18 14:24
The new bin works perfectly for me. I didn't use the volume sync tool, instead, I used PipeWire and soft mixer, but so far everything has been working perfectly. Maybe it's my ears, but I felt the left channel being a bit louder than right, but not to a point that is annoying. Anyway, no laptops have perfectly balanced speakers anyways, so I won't call it a woe.

Mark, can you verify that the new bin on yours is also working? If so, I would like to close the issue.

**Comment by mark-herbert42** [comment] 2023-11-18 18:33
Bo, Darin,

I've checked the new bin on my Yoga and it also works good. Both with alsa-controller tool and pipewire software mixer. Left, right channels in place, sounds great. So For me the issue is solved.

**Closed as completed** 2023-11-18 19:22 UTC
